name: Publish Documentation

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install DocFX
        run: dotnet tool update -g docfx

      - name: Restore projects
        run: |
          dotnet restore ATM/ATM.Domain/ATM.Domain.csproj
          dotnet restore Comportamiento/Comportamiento.Domain/Comportamiento.Domain.csproj
          dotnet restore Payment/Payment.Domain/Payment.Domain.csproj

      - name: Generate Metadata
        run: docfx metadata docs/docfx.json

      - name: Build Docs
        run: docfx build docs/docfx.json

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_site